### ISSUE TITLE
map: central african republic is not shown properly

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#136]
Please take a look at the map and specifically Africa.
There is a totally green country there: Central African Republic
However, when you move the mouse over that country, there is no pop-up / mouse-over window.

Please inspect.

Thx

**Comment by aaronkaplan** [comment]
any news on this?

**Comment by rufuspollock** [comment]
@aaronkaplan since we are dropping the map in the new version this is not a high priority. If you want we can look into it.

As a general point on process: unless a bug is absolutely critical it won't get addressed until the next sprint (in this case that starts next monday). So if you don't hear anything it does not mean we are ignoring it 😄 

At the same time, any indication of the business value of a given issue is highly appreciated. E.g. if this is esp important do let us know it!

**Comment by zelima** [comment]
WONTFIX as discussed above we are dropping maps and as there is no further response assuming this is not important
