### ISSUE TITLE
https on stats site

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#207]
Probably we do need https on stats site as well. 

If so, how will we implement it?

**Comment by aaronkaplan** [comment]
While currently technically not strictly necessary since we offer only public information, yes... it would be nice.
Our customers are the IT security community (in a wider sense including policy folks).
Therefore, SSL by default is a good thing.

How to implement it?
See: https://devcenter.heroku.com/articles/ssl-endpoint

**Comment by rufuspollock** [comment]
@zelima and @aaronkaplan we may also be able to just use cloudflare - see https://support.cloudflare.com/hc/en-us/articles/205893698-Configure-Cloudflare-and-Heroku-over-HTTPS

**Comment by zelima** [comment]
FIXED. looks like cloudflare ssl has propagated 
https://stats.cybergreen.net/

**Comment by aaronkaplan** [comment]
Yes would be good. See also pm/#89

---
Mobile
