### ISSUE TITLE
main page: map has a wrong scale (right side of the map)

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#264]
![image](https://cloud.githubusercontent.com/assets/750019/24003887/ff459f50-0a64-11e7-8234-acf5397bb657.png)

Note the scale on the right. It should be from 0 to 100.

**Comment by rufuspollock** [comment]
We checked this and oddly if you switch risk it has the right scale - and if you switch back to original risk it has the right scale!

**Comment by zelima** [comment]
FIXED
Reason here was, that scales where calculated according to "scores" of countries, that by itself where calculated according to log of DDOS units https://github.com/cybergreen-net/cg-graphs/pull/93/files#diff-bb8ca90c87cbe27648d4a822ecd86c04L105
DDOS unit numbers may be lower then 1 (and log of anything below 1 is negative) we were getting the negative scales. 
This was fixed by rounding numbers up. So anything below 1 us rounded to 1 as it does not make any difference in color coding for map
