### ISSUE TITLE
Aggregation only shows weeks in current month

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#276]
Currently we are displaying data for **latest** month (note: latest and not last full). This leads to the fact that time period that data is displayed for on `country/` is not fixed.  Eg: if today is 17 Apr will be displayed data for 2 weeks and week from now it will increase till 3.

To fix this we should either:

1. display full month
    1. Display last full calendar month
    2. Display trailing month: last month (4w) from now
       * Note: we have to do this taking account of when is most recent data
     How this works:
     Today = 17th April
     Most up to date data for any risk = 8th April
     We display 4 complete weeks before 8th april

2. switch to weekly granularity
    - display latest - 1 week
    - <del>WONTFIX. Why? Too volatile due to scanning variability. Well known problem - usually latest week does not include full scanned data for all risk and we are left with gray columns in tables. Or gray map.</del>

<del>We think the best option would be option 1.2 = the last month (4w) before our most recent data.</del>

According the analyzes we actually decided to go with option 2. See analysis below 

## Acceptance criteria 

- [ ] data for latest -1 week from db  displayed  

## Anaylzes

Shortly after diving into implementation of displaying trailing month (last 4 week) for tables and maps, we discovered that it's quite complex and needs quite careful refactor. 

Besides that what should we do when user wan't to change time granularity to let's say year or quarter - should we display last 52 year? Answer probably is no! - User wan't to see results for Eg 2014 not full 4th year from today, Or user would like to see results for 2nd quarter not results for 2nd 3 month from today.

Following the logic above only reasonable refactor to show last 4 week to display monthly results would be for only `month` granularity, which if find as temporary hack, which would be only applied to this part in API an everything else would remain same - another confusion for user. (month granularity works differently from other ones)

### Conclusion

As a conclusion we decided to use approach we were using early - *display latest -1 week from database* .

- relatively  simple and easy refactor
- no hacks - works for whole API in same way
- No confusions for user
- We remain consistent to graphs and charts on the website (graphs were always displaying weekly) 

Note: This means that there is possibility to remain with gray maps or columns, but `latest -1 week` reduces chances for that, plus data sourcing team recently is doing really good job and provides "complete" data almost in the middle of the week.

**Comment by aaronkaplan** [comment]
I don't quite agree with the WONTFIX attitude here regarding weekly data.
That was the default assumption (weekly runs, weekly measurements, weekly aggregation, display it weekly).

you say:
``
Too volatile due to scanning variability. Well known problem - usually latest week does not include full scanned data for all risk and we are left with gray columns in tables. Or gray map.
``

But that's the job of the data sourcing team . So yes, we can ask for that and that it needs to come (over time). Right now yes there might be outages. But then we simply display the last complete week. and raise an alert that some data is missing.

OR: we all collectively agree to go and only show monthly aggregates. Also possible. But then that's a decision with the data sourcing team.

**Comment by kxyne** [comment]
Why not average of last 4 weeks? It's a good indication of the trend with less spikes. We sometimes see big variations week to week for some ASNs and we're after trend rather than point in time data.

**Comment by aaronkaplan** [comment]
Also totally OK. As long as we all agree on it and understand it.

**Comment by rufuspollock** [comment]
@kxyne why not just show total of 4 weeks rather than the average then? If seems easier to implement and equally good from a UX perspective.

> But then we simply display the last complete week. 

@aaronkaplan but that then involves a bunch of complexity frontend side and on UX (e.g. what happens if latest week is different for different risks or even different countries).

**Comment by zelima** [comment]
We decided to go with weekly data. Just displaying latest -1 week as we were doing earlier to avoid  gray columns or maps as much as possible.

**Comment by zelima** [comment]
FIXED we are now showing latest -1 week
