### ISSUE TITLE
Risk page error if no data available

### ISSUE THREAD

**Issue by chorsley** [cybergreen-net/stats-new#96]
If no data is currently available for a single risk type (as of 2016-11-04, http://cybergreen-stats.herokuapp.com/risk/opendns/ displays this behaviour), an application error is produced.

As well as displaying a nice message to explain the situation rather than the error, it would also be handy to include a link to show the last data that we do actually have. This requires the ability to navigate back and forward through the weeks of data available.

**Comment by rgrp** [comment]
@chorsley good bug catch.

@zelima we need to think about right solution here and also triage this issue (how important is it - e.g. how often will we have no data for a risk ...).

I would say that 404'ing is probably not right solution as it implies page is not there rather than data not available.

**Comment by zelima** [comment]
WONTFIX this is no more relevant as we are showing time series graph on `risk-id` page
